apiVersion: apps/v1
kind: Deployment
metadata:
  name: restful-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: restful-service
  template:
    metadata:
      labels:
        app: restful-service
    spec:
      containers:
      - name: restful-service
        image: restful-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: postgres-headless
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: password
        - name: DB_NAME
          value: userdb
        - name: DB_PORT
          value: "5432"
        - name: SERVER_PORT
          value: "8080"
        resources:
          limits:
            cpu: "0.5"
            memory: 512Mi
          requests:
            cpu: "0.2"
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: swagger/index.html
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: swagger/index.html
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
      restartPolicy: Always
